FUNCTION /ODSMFE/FM_FORMS_CALL_URL.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(IM_URL) TYPE  STRING OPTIONAL
*"     REFERENCE(IM_WO) TYPE  AUFNR OPTIONAL
*"     REFERENCE(IM_MODE) TYPE  STRING DEFAULT 'workorder'
*"     REFERENCE(IM_FORMID) TYPE  /ODSMFE/DE_FORMID OPTIONAL
*"     REFERENCE(IM_BROWSER) TYPE  STRING OPTIONAL
*"     REFERENCE(IM_INSTANCEID) TYPE  /ODSMFE/DE_INSTANCEID OPTIONAL
*"     REFERENCE(IM_FUNCTION) TYPE  SALV_DE_FUNCTION OPTIONAL
*"     REFERENCE(IM_VERSION) TYPE  /ODSMFE/DE_VERSION OPTIONAL
*"     REFERENCE(IM_VORNR) TYPE  VORNR OPTIONAL
*"--------------------------------------------------------------------





ENDFUNCTION.
